Update combat.py
color_bk is a float, but used for indexing. So to work it has to be converted to int

Traceback (most recent call last):
  File "combat.py", line 145, in <module>
    background(screen, 0, WINDOWHEIGHT, colors_hex[color_bk])
TypeError: list indices must be integers or slices, not float